spring.application.name=demo

spring.security.user.name=LS
spring.security.user.password=Master

spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username=root
spring.datasource.password=testing
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
